NUTRIENTES_SUELO = [
    "M.O. %",
    "CIC meq/100g",
    "Ac. Inter. meq/100g",
    "Al Inter. meq/100g",
    "(CE) mS/cm",
    "pH  (en H2O)",
    "pH  (en KCl)",
    "(NO3-N) mg/kg",
    "(NH4-N) mg/kg",
    "(NO3+NH4) N mg/kg",
    "(P) mg/kg",
    "(K) mg/kg",
    "(Mg) mg/kg",
    "(Ca) mg/kg",
    "(SO4-S) mg/kg",
    "(Fe) mg/kg",
    "(Mn) mg/kg",
    "(Cu) mg/kg",
    "(Zn)  mg/kg",
    "(B)  mg/kg",
    "(Na)  mg/kg",
    "(Cl¯)  mg/kg",
    "Sales Totales mg/kg"
]

MAPEO_COLUMNAS = {
    "M.O. %": "Materia \nOrgánica %",
    "CIC meq/100g": "**Capacidad de Intercambio\nCatiónico - CIC\nmeq/100g",
    "Ac. Inter. meq/100g": "Acidez Inter.\nmeq/100g",
    "Al Inter. meq/100g": "Aluminio Inter.\nmeq/100g",
    "(CE) mS/cm": "Conductividad (CE)\nmS/cm",
    "pH  (en H2O)": "pH \n(en H2O)",
    "pH  (en KCl)": "pH \n(en KCl)",
    "(NO3-N) mg/kg": "Nitrato \n(NO3-N)\nmg/kg",
    "(NH4-N) mg/kg": "Amonio \n(NH4-N)\nmg/kg",
    "(NO3+NH4) N mg/kg": "(NO3+NH4)\nN\nmg/kg",
    "(P) mg/kg": "Fósforo \n(P)\nmg/kg",
    "(K) mg/kg": "Potasio \n(K)\nmg/kg",
    "(Mg) mg/kg": "Magnesio \n(Mg)\nmg/kg",
    "(Ca) mg/kg": "Calcio \n(Ca)\nmg/kg",
    "(SO4-S) mg/kg": "Azufre \n(SO4-S)\nmg/kg",
    "(Fe) mg/kg": "Hierro \n(Fe)\nmg/kg",
    "(Mn) mg/kg": "Manganeso \n(Mn)\nmg/kg",
    "(Cu) mg/kg": "Cobre \n(Cu)\nmg/kg",
    "(Zn)  mg/kg": "Zinc \n(Zn) \nmg/kg",
    "(B)  mg/kg": "Boro \n(B) \nmg/kg",
    "(Na)  mg/kg": "Sodio  \n(Na) \nmg/kg",
    "(Cl¯)  mg/kg": "Cloruro \n(Cl¯) \nmg/kg",
    "Sales Totales mg/kg": "Sales Totales\nmg/kg"
}

MAPEO_COLUMNAS_LOGICA = {
    "mo": "M.O. %",
    "cic": "CIC meq/100g",
    "acinter": "Ac. Inter. meq/100g",
    "alinter": "Al Inter. meq/100g",
    "ce": "(CE) mS/cm",
    "phh2o": "pH  (en H2O)",
    "phkcl": "pH  (en KCl)",
    "no3n": "(NO3-N) mg/kg",
    "nh4n": "(NH4-N) mg/kg",
    "no3nh4": "(NO3+NH4) N mg/kg",
    "fosforo": "(P) mg/kg",
    "potasio": "(K) mg/kg",
    "magnesio": "(Mg) mg/kg",
    "calcio": "(Ca) mg/kg",
    "azufre": "(SO4-S) mg/kg",
    "hierro": "(Fe) mg/kg",
    "manganeso": "(Mn) mg/kg",
    "cobre": "(Cu) mg/kg",
    "zinc": "(Zn)  mg/kg",
    "boro": "(B)  mg/kg",
    "sodio": "(Na)  mg/kg",
    "cloruro": "(Cl¯)  mg/kg",
    "salestotales": "Sales Totales mg/kg"
}
